-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "UserRole" AS ENUM ('admin', 'priest');

-- CreateEnum
CREATE TYPE "RequestStatus" AS ENUM ('pending', 'soil_collected', 'approved', 'rejected', 'visited', 'success', 'failure', 'on_hold');

-- CreateEnum
CREATE TYPE "RequestPriority" AS ENUM ('normal', 'urgent');

-- CreateTable
CREATE TABLE "users" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "email" STRING NOT NULL,
    "password_hash" STRING NOT NULL,
    "role" "UserRole" NOT NULL DEFAULT 'admin',
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "districts" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "state" STRING NOT NULL,

    CONSTRAINT "districts_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "mandals" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "district_id" INT4 NOT NULL,

    CONSTRAINT "mandals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "farmers" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "full_name" STRING NOT NULL,
    "purpose_of_visit" STRING,
    "phone" STRING NOT NULL,
    "village" STRING NOT NULL,
    "mandal_id" INT4 NOT NULL,
    "district_id" INT4 NOT NULL,
    "state" STRING NOT NULL,
    "pin_code" STRING NOT NULL,
    "district" STRING NOT NULL DEFAULT '',
    "subdistrict" STRING NOT NULL DEFAULT '',
    "district_geoname_id" INT4 NOT NULL DEFAULT 0,
    "farm_latitude" DECIMAL(10,8),
    "farm_longitude" DECIMAL(11,8),
    "location_verified" BOOL NOT NULL DEFAULT false,
    "address_json" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "farmers_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "requests" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "farmer_id" INT4 NOT NULL,
    "status" "RequestStatus" NOT NULL DEFAULT 'pending',
    "status_before_hold" STRING,
    "priority" "RequestPriority" NOT NULL DEFAULT 'normal',
    "notes" STRING,
    "requested_date" DATE NOT NULL,
    "expected_soil_date" DATE,
    "expected_approval_date" DATE,
    "expected_visit_date" DATE,
    "hold_reason" STRING,
    "hold_at" TIMESTAMP(3),
    "rescheduled_at" TIMESTAMP(3),
    "reschedule_reason" STRING,
    "soil_collected_date" DATE,
    "approved_date" DATE,
    "visit_date" DATE,
    "completed_date" DATE,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "requests_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "unique_district_state" ON "districts"("name", "state");

-- CreateIndex
CREATE UNIQUE INDEX "unique_mandal_district" ON "mandals"("name", "district_id");

-- CreateIndex
CREATE INDEX "idx_phone" ON "farmers"("phone");

-- CreateIndex
CREATE INDEX "idx_district" ON "farmers"("district_id");

-- CreateIndex
CREATE INDEX "idx_mandal" ON "farmers"("mandal_id");

-- CreateIndex
CREATE INDEX "idx_status" ON "requests"("status");

-- CreateIndex
CREATE INDEX "idx_priority" ON "requests"("priority");

-- CreateIndex
CREATE INDEX "idx_farmer" ON "requests"("farmer_id");

-- AddForeignKey
ALTER TABLE "mandals" ADD CONSTRAINT "mandals_district_id_fkey" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "farmers" ADD CONSTRAINT "farmers_mandal_id_fkey" FOREIGN KEY ("mandal_id") REFERENCES "mandals"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "farmers" ADD CONSTRAINT "farmers_district_id_fkey" FOREIGN KEY ("district_id") REFERENCES "districts"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "requests" ADD CONSTRAINT "requests_farmer_id_fkey" FOREIGN KEY ("farmer_id") REFERENCES "farmers"("id") ON DELETE CASCADE ON UPDATE RESTRICT;
